### PR TITLE
Added a hook for HID report notification 

### PR DESCRIPTION
**Pull request by noseglasses**
This PR adds a hook that enables other
modules to be informed about what is actually
reported.

### CODE REVIEW

**Comment by obra** [comment]
Would it work as well to add this hook in https://github.com/keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID? In theory, all Kaleidoscope access to a hid should be going through our HIDAdaptor interface.

**Comment by noseglasses** [comment]
> Would it work as well to add this hook in https://github.com/keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID? In theory, all Kaleidoscope access to a hid should be going through our HIDAdaptor interface.

Unfortunately not. That's because some attempts to send reports are ignored within KeyboardioHID.
The place where I added the hook is the only one where it is 100% sure that a report is send.

I need this for a plugin that records keyboard I/O like a flight recorder. The generated data set is meant to be fed to the simulator during test runs. By this means i want to simplify the generation of tests.

**Comment by noseglasses** [comment]
FYI, this is not meant to be used to modify keyboard reports, just to observe them and it does not need to be 100% portable over all keyboards. it is already sufficient if some of the hardwares support it.

**Comment by noseglasses** [comment]
@obra, there are some questions I am sorry to bother you with.

Currently all keyboards whose hardware is defined within the Kaleidoscope repo use Kaleidoscope-HIDAdaptor-KeyboardioHID which roots via KeyboardioHID to a common `HID` class for all HID reports. That's why it is so convenient to gather all information about reports actually send there.
I am, however, a bit confused about the naming of the libraries. Most keyboards are non-Keyboardio keyboards but still work fine with the Keyboardio-libraries. That's why I wonder what makes these two libraries/repos especially Keyboardio-ish?

Another question is about Kaleidoscope-Hardware-Virtual's design. It's original implementation copied great parts of KeyboardioHID and replaced those parts of it that called into Arduino's HID libraries. While this is a nice approach, it comes with the drawback of a lot of redundant code that diverged from the non-virtual implementation in KeyboardioHID.
Because of that, I wonder if it would be feasible to let the virtual implementation use Kaleidoscope-HIDAdaptor-KeyboardioHID and KeyboardioHID and only replace the HID-class with a virtual implementation. Buy this means, we could get rid of a lot of redundant code and get the virtual hardware closer to the physical one. Or am I possibly overlooking something here?

I stumbled upon all this in an attempt to build a workflow that would enable us to verify that the simulator does exactly behave like the physical keyboard. Before this is 100% guaranteed, using the simulator for testing is pointless. Right now there are still some differences to be sorted out but I have the feeling that I am getting closer...

**Comment by obra** [comment]
On Wed, Jun 12, 2019 at 3:14 PM noseglasses <notifications@github.com>
wrote:

> @obra <https://github.com/obra>, there are some questions I am sorry to
> bother you with.
>

No need to apologize :)

Currently all keyboards whose hardware is defined within the Kaleidoscope
> repo use Kaleidoscope-HIDAdaptor-KeyboardioHID which roots via
> KeyboardioHID to a common HID class for all HID reports. That's why it is
> so convenient to gather all information about reports actually send there.
> I am, however, a bit confused about the naming of the libraries. Most
> keyboards are non-Keyboardio keyboards but still work fine with the
> Keyboardio-libraries. That's why I wonder what makes these two
> libraries/repos especially Keyboardio-ish?
>

KeyboardioHID is "A HID implementation designed by Keyboardio" and predates
the Kaleidoscope name. In theory, it's also useful for non-Kaleidoscope
projects. If I were starting from scratch today, I might have named it
differently.

The HIDAdaptor is named to match the HID implementation. The intent there
is that we might have other, alternate HID adaptors, say for a Bluetooth HID


> Another question is about Kaleidoscope-Hardware-Virtual's design. It's
> original implementation copied great parts of KeyboardioHID and replaced
> those parts of it that called into Arduino's HID libraries. While this is a
> nice approach, it comes with the drawback of a lot of redundant code that
> diverged from the non-virtual implementation in KeyboardioHID.
> Because of that, I wonder if it would be feasible to let the virtual
> implementation use Kaleidoscope-HIDAdaptor-KeyboardioHID and KeyboardioHID
> and only replace the HID-class with a virtual implementation. Buy this
> means, we could get rid of a lot of redundant code and get the virtual
> hardware closer to the physical one. Or am I possibly overlooking something
> here?
>

The -intent- of the HIDAdaptor design was that that was exactly the layer
at which we would do something like this.


> I stumbled upon all this in an attempt to build a workflow that would
> enable us to verify that the simulator does exactly behave like the
> physical keyboard. Before this is 100% guaranteed, using the simulator for
> testing is pointless. Right now there are still some differences to be
> sorted out but I have the feeling that I am getting closer...
>

I don't think I'd say it'd be -pointless-, but 100% equivalence would be
awesome.

**Comment by noseglasses** [comment]
> The -intent- of the HIDAdaptor design was that that was exactly the layer at which we would do something like this.

That makes sense. But the HIDAdaptor library is not a true adaptor, although the name suggests it. It does a lot more as it e.g. modifies and suppresses HID reports. That's why I would rather not like to replace it with some "virtual" implementation that would be hard to maintain (due to the possible redundancies). If we want the simulator to be as close as possible to the real firmware, we should really only replace those parts that are too hardware-related to be simulated. In my opinion this applies to the HID-class only.

> I don't think I'd say it'd be -pointless-, but 100% equivalence would be awesome.

Ok, let me replace _pointless_ with _unreliable_. 

I've spend the last two decades doing all sorts of computer simulations for a living. If I learned one thing - often the hard way-, then it is that validation is absolutely crucial. A non-validated simulator is not only worthless but can even be dangerous if you trust in its results. 

Trusting a bad simulator for integration testing might cause bad PRs getting merged and breaking the firmware. That's definitely not what I have in mind.

But I am pretty confident that we can get to 100% equivalence once all the implementation details are untangled.

**Comment by obra** [comment]
On Wed, Jun 12, 2019 at 3:55 PM noseglasses <notifications@github.com>
wrote:

> The -intent- of the HIDAdaptor design was that that was exactly the layer
> at which we would do something like this.
>
> That makes sense. But the HIDAdaptor library is not a true adaptor,
> although the name suggests it. It does a lot more as it e.g. modifies and
> suppresses HID reports.
>

*sigh* It was -supposed- to be just an adaptor. But understood.


> That's why I would rather not like to replace it with some "virtual"
> implementation that would be hard to maintain (due to the possible
> redundancies). If we want the simulator to be as close as possible to the
> real firmware, we should really only replace those parts that are too
> hardware-related to be simulated. In my opinion this applies to the
> HID-class only.
>
Ok.


> I don't think I'd say it'd be -pointless-, but 100% equivalence would be
> awesome.
>
> Ok, let me replace *pointless* with *unreliable*.
>
> I've spend the last two decades doing all sorts of computer simulations
> for a living. If I learned one thing - often the hard way-, then it is that
> validation is absolutely crucial. A non-validated simulator is not only
> worthless but can even be dangerous if you trust in its results.
>
> Trusting a bad simulator for integration testing might cause bad PRs
> getting merged and breaking the firmware. That's definitely not what I have
> in mind.
>
> But I am pretty confident that we can get to 100% equivalence once all the
> implementation details are untangled.
>
Fair enough :) I certainly defer to your deeper understanding of the
pitfalls.

**Pull request merged**
