### PR TITLE
Rewrite Mouse API

### LINKED ISSUE #52: Mouse report suppression isn't quite correct
When suppressing unnecessary HID reports in [`Mouse_::sendReport()`](https://github.com/keyboardio/KeyboardioHID/blob/d60af3cf09e9a0d199f5bc393b34f15041b7090a/src/MultiReport/Mouse.cpp#L127-L130), the report is aborted only if both the previous report and the current one are empty. Because of the way mouse reports work, this isn't quite the right comparison. Instead, it should check that the mouse button state hasn't changed, and that the rest of the report (movement & scrolling) is empty.

As it is, if the user holds down a mouse _button_ key, but no movement keys, it could send repeated unnecessary reports because the report isn't entirely empty.

Furthermore, it really isn't necessary to store the whole previous report (or a `static` empty report) in RAM, as the only thing that needs checking is the previous `buttons` byte.

### PR DESCRIPTION
**Pull request by gedankenexperimenter**
This introduces a whole new mouse API, oriented better toward the needs of Kaleidoscope's MouseKeys plugin (but not limited solely to it).  Because mouse events are either buttons, cursor movement, or wheel movement, it is simpler and clearer to separate these out into three new functions:

- `sendButtonReport(buttons)`
- `sendMoveReport(x, y)`
- `sendWheelReport(v, h)`

The old Mouse report API was structurally similar to the Keyboard report API, with a full two copies of the mouse report kept at all times (the current report and the previous one).  The old report wasn't really very useful, however, because repeated mouse reports with the same values actually cause the mouse cursor to move on the host; unlike repeated identical keyboard reports, they're not a no-op.  For relative movement and wheel reports, all we need to do is suppress reports that send all zeroes for cursor and wheel movement.

We do still have a reason to store the current state of the mouse buttons, because those get sent to the host whenever a cursor or wheel movement update is sent, and we need to preserve that state.  Therefore, we do have a reason to store the last report's button state, and can do a comparison to suppress redundant button-only reports.

As a result, rather than storing two full mouse reports (three, counting the empty report used for comparison), all we need is one byte for the current button state.  And with the new API, we don't end up sending a no-op report when we get told that the mouse has stopped moving.

Fixes #52.

I'm submitting this as a draft PR for the moment.  It shouldn't get merged until the MouseKeys rewrite is ready to be merged in Kaleidoscope.

### CODE REVIEW

**Comment by gedankenexperimenter** [comment]
I'm leaning toward changing the name of `sendMoveReport()` to `sendCursorReport()`.  I think that better matches the pattern of the other functions.

**Comment by obra** [comment]
Other than the storage savings, is there a compelling reason not to leave the old 'do everything' interface around as an option? Going forward, I expect that we'll be less and less space constrained as more and more of the industry moves to more powerful microcontrollers.

**Comment by gedankenexperimenter** [comment]
The new interface also "does everything".  We don't really have either a facility or a need for sending simultaneous mouse reports of different logical types.  Button state changes, cursor movement, and wheel updates all happen independently from one another.  Even with a physical mouse, I bet you don't often get two of those changes happening in the same report very often.  This change is mostly about the API actually matching the functions that we want it to perform.  The reduction in memory footprint is a nice bonus, but less important.  This might make more sense when you see the work I've done to rewrite MouseKeys (which is what drove me to submit this change).

**Comment by obra** [comment]
Sorry, I didn't mean to suggest that the new interface was incomplete.

To slightly restate why this change feels a little off to me:

I'm not /all/ that concerned with how much storage space we need for report internals, especially going forward, although yet, it's a nice bonus.

`sendReport()` was designed to be identical across all HID devices with a meaning of 'trigger sending a report of whatever state has currently been communicated from client code'.

I 100% support a cleaner API for calling code that breaks apart button presses, scroll wheel events, and movement, but I don't believe that should require us to change the `sendReport()` pattern.

I *think* that what I'm suggesting may be as simple as making equivalents to `x,y,h,v` look more like `buttons_` but clearing them after `sendReport()` and not having `move`, a new `scroll`(?), `press` and `release` imply `sendReport()`.

**Comment by gedankenexperimenter** [comment]
I disagree with the premise that all HID reporters should have the same structure.  A Keyboard HID report doesn't directly tell the host about changes; it tells the host about the current state of the device.  A relative Mouse HID report (with the exception of the buttons byte) does tell the host about changes.  It says "move the cursor 3 pixels to the left", not "the 'move left' bit is still turned on".  When the keyboard doesn't send any report, the host doesn't stop repeating characters, but when the mouse stops sending reports, the cursor stops moving.  Forcing the mouse to have the same API structure as the keyboard doesn't make sense, especially now that Kaleidoscope itself is event driven.  This new API is a far better match for the things that Kaleidoscope actually does than the old one was.

Please take a look at the MouseKeys rewrite that I did, and I think you'll see what I'm talking about.

**Comment by gedankenexperimenter** [comment]
As a side note, I think that the other HID types would also benefit from major changes.  I would like to change the Keyboard API so that it only stores one HID report (the last one sent), and have the HID report be stored in an object that is instantiated by Kaleidoscope as needed, and passed to the HID dispatcher (which compares the new report to the old one to suppress duplicates, just in case Kaleidoscope has screwed that up (note that suppressing those reports has really become Kaleidoscope's job now that it doesn't blindly try to send one every cycle)).  This would save memory, but more important, it would confine plugins to only making changes to the HID report when it makes sense to do so.

If that change was made, the Keyboard report(er) would be much more like this new Mouse report(er).

**Comment by obra** [comment]
KeyboardioHID is, in theory, still supposed to be a general-purpose Arduino HID library and having some of the devices not follow the same high-level patterns as the others doesn't feel right to me.

That being said, I will absolutely look at this again in the context of the MouseKeys rewrite.  (My plate is a little full today, so it probably won't be before this evening or tomorrow.)

**Comment by obra** [comment]
At one point, we were talking about moving the code in KeyboardioHID into
the Kaleidoscope core. That would be a natural time to (potentially
radicaly) rethink the API. My recollection is that @algernon hit a
roadblock of some kind, but I don't 100% recall what that was.

**Comment by gedankenexperimenter** [comment]
> That being said, I will absolutely look at this again in the context of the MouseKeys rewrite. (My plate is a little full today, so it probably won't be before this evening or tomorrow.)

Before you do that, I would like to get keyboardio/Kaleidoscope#1114 merged, if you're willing (I don't mean before this evening; I mean before continuing the examination of this API change and the MouseKeys rewrite).

**Comment by obra** [comment]
Got it. I will absolutely prioritize that over this.

**Comment by gedankenexperimenter** [comment]
I'm continuing to mull this over.  I went back and had a look at how I did this in Kaleidoglyph (which used a HID library that separated things into a `Report` object that contains the data and a `Dispatcher` object that sends reports).  With that model, there's only one `Dispatcher::sendReport()` function; when "Squeakeys" (the name I used for MouseKeys) wants to send a report, it creates a `Report` object, calls methods to set whatever values it needs to, then passes a reference to that `Report` to the `Dispatcher` object's `sendReport()` function.

I can easily be convinced now that a much smaller change (to just fix the problems of extra reports being sent) is appropriate here, and a more radical change to the API (possibly bringing KeyboardioHID into Kaleidoscope) should be pushed off to a separate project.

One key question that I have, which I don't know the answer to: are there any Kaleidoscope devices out there that _don't_ use KeyboardioHID?  If so, this all gets trickier.

**Comment by obra** [comment]
> One key question that I have, which I don't know the answer to: are there any Kaleidoscope devices out there that don't use KeyboardioHID? If so, this all gets trickier.

There aren't today, but for example, we'd need that if we wanted to port to your preonic. 

We do have a layer of indirection for this in the Kaleidoscope src/kaleidoscope/driver/hid/ facade.

**Comment by gedankenexperimenter** [comment]
> There aren't today, but for example, we'd need that if we wanted to port to your preonic.

Yeah, I knew that.  Changing the API for future devices is easy, though. =)

**Comment by obra** [comment]
Sure. It might be worth looking at how the HID libraries work for other
potential targets to understand what we're going to have to fit to before
radically retooling ours.

https://github.com/adafruit/Adafruit_TinyUSB_Arduino
https://github.com/stm32duino/Arduino_Core_STM32/tree/main/libraries
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/USBComposite

are the three that come to mind (other than vanilla Arduino)

**Comment by gedankenexperimenter** [comment]
I'm closing this one, at least for now, since the plan is to first bring the HID library into Kaleidoscope as a driver, and then a more comprehensive update to the Kaleidoscope HID façade.

**Pull request closed without merging**
