### PR TITLE
Allow building against cores with no USB or PluggableUSB

### PR DESCRIPTION
**Pull request by wez**
It may sound pointless, but this library is pulled in whenever
we want to reference the HID headers.  Allow compiling the
cpp files into nothing in such an environment.

### CODE REVIEW

**Comment by obra** [comment]
Checking for !CORE_TEENSY feels a little weird to me. Is there something more duck-typey we could check instead? Or at least lift the composite condition out to a single macro. (That'd make it less likely for variants to creep in or for someone to screw up the check when adding new code that needs the guard)

Alternatively, this seems like a compelling reason to maybe aplit out the headers to their own library.

**Comment by wez** [comment]
According to https://github.com/arduino/Arduino/wiki/PluggableUSB-and-PluggableHID-howto you can detect PluggableUSB by including HID.h and then testing for a symbol.  Teensy doesn't have HID.h though :-/

I'll clean this up and make it a bit less repetitious.

**Comment by wez** [comment]
I restructured as follows:

* Added `HID-Compatibility.h` and made it responsible for defining the symbol `KEYBOARDIO_HAS_PLUGGABLE_USB` if we can use that interface
* On Teensy, the various `KEY_XXX` symbols are already defined to thing that conflict horribly with the defines in `HIDAliases.h`.  It appears to be "fine" to just not define those symbols when building against teensy.  I'm wondering if we can just remove those, or where those are consumed so that we can fixup the namespacing?

**Comment by wez** [comment]
(I force-pushed those changes, so you'll need to force a refresh in the github UI for it to realize and show you the right things)

**Comment by obra** [comment]
Reviewing this code, I see that you didn't touch this guard code in KeyboardioHID.h:
 y 
 #if !defined(USBCON)
 #error HID Project can only be used with an USB MCU.
 #endif

It seems like the new guard would only apply to the teensy. is that right?

**Comment by obra** [comment]
Also, a minor thing for the future: If it's possible to separate out commits more granularly, that'd be great. Here, I'd probably break out the .gitignore, the KEY_XXX macros and the new guard code into three commits.

I'm going to apply the KEY_XXX stuff and the .gitignore stuff by hand now

**Comment by obra** [comment]
@wez - I've been continuing to ponder this change. Is it the case that the only reason you're including KeyboardioHID at this point is to get the HID Tables? If so, I think that's a good argument for lifting them to Kaleidoscope. 
I'm happy to do that work, but want to make sure I'm doing the right thing for you.

**Comment by obra** [comment]
Closing this out. Our HIDAdaptor abstraction provides the rope one needs to use alternate HID implementations.

**Pull request closed without merging**
