### PR TITLE
Support for horizontal mouse wheel movement.

### PR DESCRIPTION
**Pull request by SjB**
Extended the HID Descriptor to send a Consumer Device page
that support a horizontal mouse scroll wheel

### CODE REVIEW

**Comment by obra** [comment]
Hi Steve,

Thanks so much for the PRs!

I'd love to know more about the use case (I don't think I've seen a mouse
with dual scroll wheels).

As concrete first comments on this and the associated pull requests:

* I'd love it if you could update sample code with usage of the new feature
and comments explaining the expected behavior
* Right now, the pull requests appear to break the mouse API. If you can
add compatibility wrappers, that should take care of that.

**Comment by SjB** [comment]
@obra 

To start with the feature should is **Support for horizontal mouse wheel**, major typo on my part. I use the mouse wheel to scroll up, down, left, right when I'm look at documents. On many coding website when code sample are shown in text box the text box has a horizontal scroll bar and it's just easier for me to use the keyboard to scroll the content with the keyboard keys.

**Comment by algernon** [comment]
The build failure is due to an out-of-date Arduino-Boards. If retried, it should pass now.

**Comment by obra** [comment]
The build failure is due to getting the wrong 'HID' library.  But merging :)

**Comment by obra** [comment]
Thanks! Applied.

**Pull request merged**
