### PR TITLE
Keyboard: Don't skip NONUS_POUND and CLEAR

### PR DESCRIPTION
**Pull request by algernon**
To be able to send NONUS_POUND and CLEAR keycodes, we need our report bitmap to support them, and not mask them over with constants. These were originally masked due to bugs in the Linux kernel, which allegedly resulted in double presses when these codes were in the report. If they are not in the report, they should not cause issues, and one may want to use the codes anyway.

Therefore, this patch removes this mask, and only the first four bits remain masked.

Fixes keyboardio/Kaleidoscope#273.

### CODE REVIEW

**Comment by algernon** [comment]
Note to self: push my findings from my [worklog](https://github.com/algernon/keyboardio-worklog/blob/master/worklog.md#2017-12-20) into the commit message.

**Comment by algernon** [comment]
Pushed an updated commit, with much more reasoning within it.

**Comment by algernon** [comment]
@obra Do you have any concerns? This fixes a legitimate issue for non-Linux users (especially international users, where NonUSPound is often used for localized keymaps), and as far as I was able to check, causes no issues under Linux either.

Would be great to have this in, so people trying their hands on localized layouts will be able to use `NonUSPound`.

**Comment by obra** [comment]
Sure, I'm willing to try it.

**Pull request merged**
