### PR TITLE
Port the library to Atmel SAMD

### PR DESCRIPTION
**Pull request by algernon**
The port is heavily based on [NicoHood/HID](https://github.com/NicoHood/HID)'s port, but it was tweaked in a few small ways for KeyboardioHID: I split it into smaller commits, and enabled host wakeup in SystemControl.

It compiles, and appears to work on real hardware too, but has seen only light testing on SAMD so far. The AVR functionality should be unaffected.

### CODE REVIEW

**Comment by obra** [comment]
"src/port/samd.cpp"

"port" seems like a weird name for that.

**Comment by algernon** [comment]
How about `src/arch/samd.cpp`? (`src/port/samd.cpp` is how it's called in the original)

**Comment by obra** [comment]
sure
ᐧ

**Comment by algernon** [comment]
Done.

Also rolled in another update, making `GET_PROTOCOL` and `GET_IDLE` work on SAMD too.

**Comment by obra** [comment]
Is the latest rev tested on AVR?
ᐧ

**Comment by algernon** [comment]
Yes, compiles and works fine too. At least normal keycodes come through, I haven't tested everything yet, but my gut feeling is that if anything broke, normal keycodes wouldn't work either.

**Pull request merged**
