### PR TITLE
Adaptions to share implementation with the virtual hardware

### PR DESCRIPTION
**Pull request by noseglasses**
This PR is a part of https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio/pull/18

### CODE REVIEW

**Comment by obra** [comment]
I'm willing to merge this, but looking at it, I realize we probably shouldn't be creating preprocessor macros starting with "ARDUINO"

**Comment by noseglasses** [comment]
Exactly. What would you prefer instead?

**Comment by obra** [comment]
@noseglasses A good question! KEYBOARDIOHID_BUILD_FOR_SIMULATION? KEYBOARDIOHID_BUILD_WITHOUT_HID? It's verbose, but this is a "weird" thing we're doing here.

**Comment by noseglasses** [comment]
The macro `ARDUINO_VIRTUAL` was introduced with Kaleidoscope-Hardware-Virtual. It is defined in platforms.txt for the virtual architecture.

Currently it is used in the following files
```
KeyboardioHID/src/HID.cpp
Kaleidoscope/src/kaleidoscope/plugin/Qukeys.cpp
Kaleidoscope/src/kaleidoscope/plugin/Model01-TestMode.h
Kaleidoscope/src/kaleidoscope/plugin/FirmwareDump.cpp
Kaleidoscope/src/kaleidoscope/plugin/Model01-TestMode.cpp
Kaleidoscope/src/kaleidoscope/plugin/FirmwareDump.h
Kaleidoscope/src/kaleidoscope/hardware/keyboardio/Model01.cpp
Kaleidoscope/src/kaleidoscope_internal/LEDModeManager.h
```
This shows that it is not directly related to HID but informs the whole firmware that it is currently build for the virtual architecture and that specific parts of the code are not meant to be build.

What about `KALEIDOSCOPE_VIRTUAL_BUILD`?

**Comment by obra** [comment]
I'm ok with the KALEIDOSCOPE_VIRTUAL_BUILD macro for stuff -inside-
KALEIDOSCOPE, but KeyboardioHID is supposed to be able to stand alone and
not know anything about KALEIDOSCOPE. If defining
KALEIDOSCOPE_VIRTUAL_BUILD also defines the macro we need inside
KeyboardioHID, I think this can get me what I want without being too
burdensome.

-j

**Comment by noseglasses** [comment]
Ok, then let's go with `KEYBOARDIOHID_BUILD_WITHOUT_HID` for KeyboardioHID and 
`KALEIDOSCOPE_VIRTUAL_BUILD` for the rest of Kaleidoscope.

**Comment by obra** [comment]
Sold :)

**Pull request merged**
